version: '3'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: web
    networks:
      - node-network
    ports:
      - "8080:80"
  app:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: app
    entrypoint: dockerize --wait tcp://db:3306 --timeout 20s docker-entrypoint.sh
    command: node server.js
    networks:
      - node-network
    ports:
      - "3000:3000"
    tty: true
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    networks:
      - node-network

networks:
  node-network:
    driver: bridge